CREATE TABLE Ator(
CODIGO_ATOR INT CONSTRAINT PK_CODIGOATOR PRIMARY KEY IDENTITY(1,1),
NOME_ATOR varchar(20) CONSTRAINT NN_NOMEATOR NOT NULL,
IDADE int CONSTRAINT NN_IDADE NOT NULL,
CIDADE_ATOR varchar(20) CONSTRAINT NN_CIDADEATOR NOT NULL,
SALARIO_ATOR DECIMAL(10,2) CONSTRAINT NN_SALARIOATOR NOT NULL,
SEXO_ATOR varchar(3) CONSTRAINT CK_SEXOATOR CHECK (SEXO_ATOR IN ('M', 'F', 'NB', 'O'))
);

CREATE TABLE Novela(
CODIGO_NOVELA INT CONSTRAINT PK_CODIGONOVELA PRIMARY KEY IDENTITY(1,1),
NOME_NOVELA varchar(30) CONSTRAINT NN_NOMENOVELA NOT NULL,
DATA_PRIMEIRO_CAPITULO DATE CONSTRAINT NN_DATAPRIMEIROCAPITULO NOT NULL,
DATA_ULTIMO_CAPITULO DATE,
HORARIO_EXIBICAO TIME CONSTRAINT NN_HORARIOEXIBICAO NOT NULL
);

CREATE TABLE Capitulos(
CODIGO_CAPITULO INT CONSTRAINT PK_CODIGOCAPITULO PRIMARY KEY IDENTITY(1,1),
NOME_CAPITULO varchar(50) CONSTRAINT NN_NOMECAPITULO NOT NULL,
DATA_EXIBICAO_CAPITULO DATE CONSTRAINT N_DATAEXIBICAOCAPITULO NULL,
CODIGO_NOVELA INT CONSTRAINT NN_NOVELACAPITULO NOT NULL,
CONSTRAINT FK_NOVELACAPITULO FOREIGN KEY (CODIGO_NOVELA) REFERENCES NOVELA(CODIGO_NOVELA)
);

CREATE TABLE Personagem(
CODIGO_PERSONAGEM INT CONSTRAINT PK_CODIGOPERSONAGEM PRIMARY KEY IDENTITY(1,1),
NOME_PERSONAGEM varchar(50) CONSTRAINT NN_NOMEPERSONAGEM NOT NULL,
IDADE_PERSONAGEM INT CONSTRAINT CK_IDADEPERSONAGEM CHECK (IDADE_PERSONAGEM >=0),
SITUACAO_FINANCEIRA_PERSONAGEM varchar(20) CONSTRAINT NN_SITUACAOFINANCEIRAPERSONAGEM NOT NULL,
CODIGO_ATOR INT CONSTRAINT NN_CODIGOATOR NOT NULL,
CONSTRAINT FK_ATORPERSONAGEM FOREIGN KEY (CODIGO_ATOR) REFERENCES ATOR(CODIGO_ATOR)
);

CREATE TABLE NovelaPersonagem(
CODIGO_NOVELA INT CONSTRAINT NN_CODIGONOVELA_NP NOT NULL,
CODIGO_PERSONAGEM INT CONSTRAINT NN_CODIGOPERSONAGEM_NP NOT NULL,
	CONSTRAINT PK_NOVELAPERSONAGEM PRIMARY KEY (CODIGO_NOVELA, CODIGO_PERSONAGEM),
	CONSTRAINT FK_NOVELAPERSONAGEM_NOVELA FOREIGN KEY (CODIGO_NOVELA) REFERENCES NOVELA(CODIGO_NOVELA),
	CONSTRAINT FK_NOVELAPERSONAGEM_PERSONAGEM FOREIGN KEY (CODIGO_PERSONAGEM) REFERENCES PERSONAGEM(CODIGO_PERSONAGEM)
);
