CREATE TABLE Treinadores(
id_treinador INT CONSTRAINT PK_ID_TREINADOR PRIMARY KEY IDENTITY(1,1),
nome varchar(100) CONSTRAINT NN_NOME NOT NULL,
data_post DATE CONSTRAINT NN_DATA NOT NULL,
posts INT CONSTRAINT DF_POSTS DEFAULT 1
);

SELECT *
FROM TREINADORES
ORDER BY data_post;

INSERT INTO Treinadores(nome, data_post)
VALUES ('Vitor Pereira', '2025-05-03')

SELECT TOP 15 nome, COUNT(nome) AS 'Número de Posts'
FROM TREINADORES
GROUP BY nome
ORDER BY COUNT(nome) DESC;