SELECT 
    V.IDVOO AS NumeroVoo,
    A_Origem.NOME AS AeroportoOrigem,
    A_Destino.NOME AS AeroportoDestino,
    V.DATA_VOO AS DataHoraVoo,
    V.PORTAOEMBARQUE AS PortaoEmbarque,
    V_CONEXAO.IDVOO AS NumeroConexao,
    V_CONEXAO.DATA_VOO AS DataHoraConexao,
    V_CONEXAO.PORTAOEMBARQUE AS PortaoConexao
FROM Voo V
INNER JOIN Aeroporto A_Origem ON V.ORIGEM = A_Origem.IDAEROPORTO
INNER JOIN Aeroporto A_Destino ON V.DESTINO = A_Destino.IDAEROPORTO
LEFT JOIN Voo V_CONEXAO ON V.CONEXAO = V_CONEXAO.IDVOO
WHERE CAST(V.DATA_VOO AS DATE) BETWEEN '2025-04-12' AND '2025-04-13'
ORDER BY V.DATA_VOO;

SELECT 
    V.IDVOO,
    V.DATA_VOO,
    V.PORTAOEMBARQUE
FROM Voo V
LEFT JOIN Aeroporto A_Conexao ON V.CONEXAO = A_Conexao.IDAEROPORTO
WHERE V.CONEXAO IS NULL 
   OR A_Conexao.NOME = 'AFONSO PENNA'
ORDER BY V.DATA_VOO;

SELECT 
    MODELO,
    AVG(CAPACIDADE) AS MediaCapacidade
FROM Aeronave
GROUP BY MODELO
HAVING AVG(CAPACIDADE) > 50
ORDER BY MediaCapacidade DESC;

SELECT 
    P.SOBRENOME + ', ' + P.NOME AS Passageiro,
    V.IDVOO AS NumeroVoo,
    V.DATA_VOO AS DataHoraEmbarque,
    V.PORTAOEMBARQUE AS PortaoEmbarque,
    A_Origem.NOME AS AeroportoOrigem,
    A_Destino.NOME AS AeroportoDestino,
    PV.ASSENTO AS Poltrona
FROM PASSAGEIRO_VOO PV
INNER JOIN Passageiro P ON PV.PASSAGEIRO = P.IDPASSAGEIRO
INNER JOIN Voo V ON PV.VOO = V.IDVOO
INNER JOIN Aeroporto A_Origem ON V.ORIGEM = A_Origem.IDAEROPORTO
INNER JOIN Aeroporto A_Destino ON V.DESTINO = A_Destino.IDAEROPORTO
ORDER BY Passageiro;

SELECT 
    IDAEROPORTO,
    NOME,
    CIDADE,
    ESTADO,
    SIGLA
FROM Aeroporto
WHERE ESTADO = 'SP';

SELECT DISTINCT
    P.CPF,
    P.NOME,
    P.SOBRENOME
FROM Passageiro P
INNER JOIN PASSAGEIRO_VOO PV ON P.IDPASSAGEIRO = PV.PASSAGEIRO
INNER JOIN Voo V ON PV.VOO = V.IDVOO
INNER JOIN Aeroporto A_Origem ON V.ORIGEM = A_Origem.IDAEROPORTO
INNER JOIN Aeroporto A_Destino ON V.DESTINO = A_Destino.IDAEROPORTO
WHERE A_Origem.ESTADO = 'SP' OR A_Destino.ESTADO = 'SP'
ORDER BY P.SOBRENOME, P.NOME;

SELECT 
    A.MODELO,
    A.CAPACIDADE,
    COUNT(V.IDVOO) AS TotalVoos
FROM Aeronave A
LEFT JOIN Voo V ON A.IDAERONAVE = V.AERONAVE
GROUP BY A.IDAERONAVE, A.MODELO, A.CAPACIDADE
ORDER BY TotalVoos DESC;

SELECT 
    A.IDAERONAVE,
    A.MODELO,
    A.CAPACIDADE
FROM Aeronave A
LEFT JOIN Voo V ON A.IDAERONAVE = V.AERONAVE
WHERE V.IDVOO IS NULL
ORDER BY A.MODELO;

-- Cidades e estados de ORIGEM de voos
SELECT 
    CIDADE,
    ESTADO
FROM Aeroporto A
INNER JOIN Voo V ON A.IDAEROPORTO = V.ORIGEM

UNION

-- Cidades e estados de DESTINO de voos  
SELECT 
    CIDADE,
    ESTADO
FROM Aeroporto A
INNER JOIN Voo V ON A.IDAEROPORTO = V.DESTINO

ORDER BY ESTADO, CIDADE;

SELECT 
    IDVOO,
    DATA_VOO,
    DATEDIFF(DAY, DATA_VOO, GETDATE()) AS DiasAteHoje
FROM Voo
WHERE DATEDIFF(DAY, DATA_VOO, GETDATE()) > 145
ORDER BY DATA_VOO DESC;