DROP DATABASE EMPRESA;

CREATE DATABASE EMPRESA;
USE EMPRESA;
	
CREATE TABLE EMPREGADO
(
	RG NUMERIC(10) CONSTRAINT PK_EMPREGADO  PRIMARY KEY,
	NOME VARCHAR(100) CONSTRAINT NN_NOME NOT NULL,
	CPF NUMERIC(11) CONSTRAINT UN_CPF UNIQUE,
	DEPARTAMENTO INT CONSTRAINT NN_DEPARTAMENTO NOT NULL,
	RGSUPERVISOR NUMERIC(10) CONSTRAINT FK_EMPREGADO REFERENCES EMPREGADO(RG),
	SALARIO NUMERIC(10,2) CONSTRAINT NN_SALARIO NOT NULL
);

CREATE TABLE DEPARTAMENTO
(
	NUMERO INT CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY IDENTITY (1,1),
	NOME VARCHAR(100) CONSTRAINT NN_NOME_DEP NOT NULL,
	RGGERENTE NUMERIC(10) CONSTRAINT NNRGERENTE NOT NULL CONSTRAINT FK_GERENTE REFERENCES EMPREGADO(RG)
);

CREATE TABLE PROJETO
(
	NUMERO INT CONSTRAINT PK_PROJETO PRIMARY KEY IDENTITY (1,1),
	NOME VARCHAR(100) CONSTRAINT NN_NOME_PROJETO NOT NULL,
	LOCALIZACAO VARCHAR(50) CONSTRAINT NN_LOCALIZACAO NOT NULL
);

CREATE TABLE DEPENDENTE
(
	NUMERODEPENDENTE INT CONSTRAINT PK_DEPENDENTE PRIMARY KEY IDENTITY(1,1),
	RGRESPONSAVEL NUMERIC(10),
	NOMEDEPENDENTE VARCHAR(100),
	CONSTRAINT UN_RGRESPONSAVELNOME UNIQUE (RGRESPONSAVEL,NOMEDEPENDENTE),
	CONSTRAINT FK_RGRESPONSAVEL FOREIGN KEY (RGRESPONSAVEL) REFERENCES EMPREGADO(RG),
	DTNASCIMENTO DATE CONSTRAINT NN_DTNASCIMENTO NOT NULL,
	RELACAO VARCHAR(30) CONSTRAINT NN_RELACAO NOT NULL,
	SEXO CHAR(1) CONSTRAINT CK_SEXO CHECK(SEXO IN('M','F')) NOT NULL
);

CREATE TABLE DEPARTAMENTOPROJETO
(
	NUMERODEPARTAMENTO INT,
	NUMEROPROJETO INT,
	CONSTRAINT PK_DEPARTAMENTOPROJETO PRIMARY KEY (NUMERODEPARTAMENTO,NUMEROPROJETO),
	CONSTRAINT FK_NUMERODEPARTAMENTO FOREIGN KEY (NUMERODEPARTAMENTO) REFERENCES DEPARTAMENTO(NUMERO),
	CONSTRAINT FK_NUMEROPROJETO FOREIGN KEY (NUMEROPROJETO) REFERENCES PROJETO(NUMERO)
);

CREATE TABLE EMPREGADOPROJETO
(
	RGEMPREGADO NUMERIC(10),
	NUMEROPROJETO INT,
	CONSTRAINT PK_EMPREGADOPROJETO PRIMARY KEY (RGEMPREGADO,NUMEROPROJETO),
	CONSTRAINT FK_RGEMPREGADO FOREIGN KEY (RGEMPREGADO) REFERENCES EMPREGADO(RG),
	CONSTRAINT FK_NUMEROPROJETO_EMPREGADOPROJETO FOREIGN KEY (NUMEROPROJETO) REFERENCES PROJETO(NUMERO),
	HORAS INT CONSTRAINT NN_HORAS NOT NULL
);

-- INSERTS

INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (10101010, 'João Luiz',11111111,1,null,3000.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (20202020, 'Fernando',22222222,2,10101010,2500.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (30303030, 'Ricardo',33333333,2,10101010,2300.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (40404040, 'Jorge',44444444,2,20202020,4200.00);
INSERT INTO EMPREGADO (RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO)
VALUES (50505050, 'Renato',55555555,3,20202020,1300.00);

INSERT INTO DEPARTAMENTO(NOME, RGGERENTE)
VALUES ('Contabilidade',10101010);
INSERT INTO DEPARTAMENTO(NOME, RGGERENTE)
VALUES ('Engenharia Civil',30303030);
INSERT INTO DEPARTAMENTO(NOME, RGGERENTE)
VALUES ('Engenharia Mec�nica',20202020);

ALTER TABLE EMPREGADO
ADD CONSTRAINT FK_DEPARTAMENTO_EMPREGADO FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (NUMERO);

INSERT INTO PROJETO(NOME, LOCALIZACAO)
VALUES ('Financeiro 1', 'S�o Paulo');
INSERT INTO PROJETO(NOME, LOCALIZACAO)
VALUES ('Motor 3', 'Rio Claro');
INSERT INTO PROJETO(NOME, LOCALIZACAO)
VALUES ('Predio Central', 'Campinas');

INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(10101010,'Jorge','1986-12-27','Filho','M');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(10101010,'Luiz','1979-11-18','Filho','M');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(20202020,'Fernanda','1969-02-14','Conjuge','F');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(20202020,'Angelo','1995-02-10','Filho','M');
INSERT INTO DEPENDENTE(RGRESPONSAVEL,NOMEDEPENDENTE,DTNASCIMENTO,RELACAO,SEXO)
VALUES(30303030,'Andreia','1990-05-01','Filho','F');
										  
INSERT INTO DEPARTAMENTOPROJETO(NUMERODEPARTAMENTO,NUMEROPROJETO)
VALUES (2,1);
INSERT INTO DEPARTAMENTOPROJETO(NUMERODEPARTAMENTO,NUMEROPROJETO)
VALUES (3,2);
INSERT INTO DEPARTAMENTOPROJETO(NUMERODEPARTAMENTO,NUMEROPROJETO)
VALUES (2,3);

INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (20202020,1,10);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (20202020,2,20);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (30303030,1,35);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (40404040,3,50);
INSERT INTO EMPREGADOPROJETO(RGEMPREGADO,NUMEROPROJETO,HORAS)
VALUES (50505050,3,35);

------------------------------------------------------------------------------------------ CONTEUDO AULA --------------------------------------------------------------------------------------

-- ORDENAÇÃO --
-- ORDER BY --
SELECT NOME FROM EMPREGADO
ORDER BY NOME DESC

SELECT NOME, CPF FROM EMPREGADO
ORDER BY NOME ASC, RG

-- NULL --
SELECT NOME FROM EMPREGADO WHERE RGSUPERVISOR IS NULL

SELECT NOME FROM EMPREGADO WHERE RGSUPERVISOR IS NOT NULL

-- LIKE E = --

SELECT NOME FROM EMPREGADO WHERE NOME LIKE 'JOÃO %'
SELECT NOME FROM EMPREGADO WHERE NOME = 'JOÃO'
SELECT NOME FROM EMPREGADO WHERE NOME LIKE '_____'

-- BETWEEN --
SELECT NOMEDEPENDENTE FROM DEPENDENTE WHERE DTNASCIMENTO BETWEEN '01-01-2000' AND '31-12-2025'

-- IN E NOT IN --
SELECT NOME FROM EMPREGADO WHERE RG IN (10101010,20202020)
SELECT NOME FROM EMPREGADO WHERE RGSUPERVISOR IN (SELECT RG FROM EMPREGADO WHERE RGSUPERVISOR IS NULL)

-- UNION --
SELECT NOME FROM EMPREGADO UNION SELECT NOME FROM EMPREGADO

SELECT NOME FROM EMPREGADO WHERE RG = 10101010 INTERSECT SELECT NOME FROM EMPREGADO

-- EXCEPT --
SELECT NOME FROM EMPREGADO WHERE RG!=10101010


----------------------------------------------------------------- LISTA DE EXERCICIOS ---------------------------------------------------------------------------------------

-- 1) Exiba todos os atributos da tabela empregado ordenando por salário e nome --
-- SELECT * FROM EMPREGADO ORDER BY SALARIO DESC, NOME DESC
SELECT RG,NOME,CPF,DEPARTAMENTO,RGSUPERVISOR,SALARIO
FROM EMPREGADO ORDER BY SALARIO, NOME

-- 2) Exiba o nome e o salário dos empregados que tem salário entre 2 e 3 mil. --
SELECT SALARIO,NOME
FROM EMPREGADO WHERE SALARIO BETWEEN 2000.00 AND 3000.00

-- 3) Exiba os dependentes que são filhos, que nasceram entre 10 de abril de 1994 e 15 de maio de 2000 e que são do sexo masculino. --
SELECT NOMEDEPENDENTE
FROM DEPENDENTE WHERE RELACAO = 'Filho' AND DTNASCIMENTO BETWEEN '1994-04-10' AND '2000-05-15' AND SEXO = 'M'

-- 4) Exiba todos os dependentes que tem Maria em qualquer parte do nome --
SELECT NOMEDEPENDENTE
FROM DEPENDENTE WHERE NOMEDEPENDENTE LIKE '% MARIA %'

-- 5) Exiba os departamentos cujo o nome tem 10 caracteres --
SELECT NOME
FROM DEPARTAMENTO WHERE NOME LIKE '__________'

-- 6) Exiba todos os empregados que possuem supervisor --
SELECT NOME
FROM EMPREGADO WHERE RGSUPERVISOR IS NOT NULL

-- 7) Exiba todos os empregados que não possuem um supervisor --
SELECT NOME
FROM EMPREGADO WHERE RGSUPERVISOR IS NULL

-- 8) Exiba uma listagem única com todos os nomes dos empregados e dependentes, caso exista nome repetidos
-- ambos devem ser exibidos --
SELECT NOME
FROM EMPREGADO UNION ALL SELECT NOMEDEPENDENTE FROM DEPENDENTE

-- 9) Exiba os empregados que possuem dependentes ou que trablaham em algum projeto. 
SELECT NOME 
FROM EMPREGADO WHERE RG IN (SELECT RGResponsavel FROM DEPENDENTE) 
OR RG IN (SELECT RGEmpregado FROM EMPREGADOPROJETO); ------------ IMPORTANTE

-- 10) Exiba os empregados que tem salário maior que 4 mil e que não tem supervisor
SELECT NOME
FROM EMPREGADO WHERE SALARIO > 4000 AND RGSUPERVISOR IS NULL

-- 11) Exiba os empregados que possuem o João Luiz como supervisor
SELECT NOME
FROM EMPREGADO WHERE RGSUPERVISOR IN (SELECT RG FROM EMPREGADO WHERE NOME LIKE 'João Luiz')

-- 12) Exiba os empregados que trabalham no projeto motor 3
-- SELECT NOME
-- FROM EMPREGADO WHERE DEPARTAMENTO = 3
SELECT NOME FROM EMPREGADO
WHERE RG IN (SELECT RGEMPREGADO FROM EMPREGADOPROJETO WHERE NUMEROPROJETO IN (SELECT NUMERO FROM PROJETO WHERE NOME LIKE 'MOTOR 3'))

-- 13) Exiba o nome dos empregados que trabalharam mais que 5 horas no projeto Prédio Central
SELECT NOME 
FROM EMPREGADO
WHERE RG IN (
    SELECT RGEMPREGADO 
    FROM EMPREGADOPROJETO 
    WHERE HORAS > 5 
    AND NUMEROPROJETO IN (
        SELECT NUMEROPROJETO   -- ← Use a CHAVE (INT), não o NOME (VARCHAR)
        FROM PROJETO 
        WHERE NOME = 'Predio Central'
    )
);

-- 14) Exiba o departamento que é gerenciado pelo empregado Ricardo
SELECT NOME FROM DEPARTAMENTO
WHERE RGGERENTE IN (SELECT RG FROM EMPREGADO WHERE NOME LIKE 'RICARDO')


------------------------------- LISTA DE EXERCICIOS TENTATIVA O1 ------------------------------------------------
-- Ordenar todos os atriutos da tabela emprego por salário e nome
SELECT *
FROM EMPREGADO
ORDER BY SALARIO, NOME

-- Exiba o nome e o salário dos empregados que tem salário entre 2 e 3 mil.
SELECT NOME, SALARIO
FROM EMPREGADO
WHERE SALARIO BETWEEN 2000.00 AND 3000.00

-- Exiba os dependentes que são filhos, que nasceram entre 10 de abril de 1994 e 15 de maio de 2000 e que são do sexo masculino
SELECT NOMEDEPENDENTE
FROM DEPENDENTE
WHERE DTNASCIMENTO BETWEEN '1994-04-10' AND '2000-05-15' AND SEXO = 'M'

-- Exiba todos os dependentes que tem MARIA em qualquer parte do nome
SELECT NOMEDEPENDENTE
FROM DEPENDENTE
WHERE NOMEDEPENDENTE LIKE '% MARIA %'

-- Exiba os departamentos cujo o nome tem 10 caracteres
SELECT NOME
FROM DEPARTAMENTO
WHERE NOME LIKE '_________'

-- Exiba todos os empregados que possuem supervisor
SELECT NOME
FROM EMPREGADO
WHERE RGSUPERVISOR IS NOT NULL

-- Exiba todos os empregados que não possuem supervisor
SELECT NOME
FROM EMPREGADO
WHERE RGSUPERVISOR IS NULL

-- Exiba uma listagem unica com todos os nomes dos empregados e dependentes, caso exista nome repetidos, ambos devem ser exibidos.
SELECT NOME
FROM EMPREGADO
UNION ALL SELECT NOMEDEPENDENTE FROM DEPENDENTE

-- Exiba os empregados que possuem dependentes ou que trabalham em algum projeto
SELECT NOME FROM EMPREGADO WHERE RG IN (SELECT RGRESPONSAVEL FROM DEPENDENTE) OR RG IN (SELECT RGEMPREGADO FROM EMPREGADOPROJETO)

-- Exiba os empregados que tem salário amior que 4 mil e que não tem supervisor
SELECT NOME FROM EMPREGADO
WHERE SALARIO > 4000 AND RGSUPERVISOR IS NULL

-- Exiba os empregados que tem o João Luis como supervisor
SELECT NOME FROM EMPREGADO
WHERE RGSUPERVISOR IN (SELECT RG FROM EMPREGADO WHERE NOME LIKE 'João Luiz')

-- Exiba os empregados que trabalham no projeto Motor 3
SELECT NOME FROM EMPREGADO 
WHERE RG IN (SELECT RGEMPREGADO FROM EMPREGADOPROJETO WHERE NUMEROPROJETO IN (SELECT NUMERO FROM PROJETO WHERE NOME LIKE 'Motor 3'))

-- Exiba o nome dos empregados que trabalharam mais do que 5 horas no projeto Prédio Central.
-- Predio Central = Numero de Projeto 20
SELECT NOME FROM EMPREGADO
WHERE RG IN (SELECT RGEMPREGADO FROM EMPREGADOPROJETO WHERE HORAS > 5 AND NUMEROPROJETO IN (SELECT NUMERO FROM PROJETO WHERE NOME LIKE 'Predio Central'))

-- Exiba o departamento que é gerenciado pelo empregado Ricardo
SELECT NOME FROM DEPARTAMENTO
WHERE RGGERENTE IN (SELECT RG FROM EMPREGADO WHERE NOME LIKE 'Ricardo')