CREATE DATABASE Aeroporto
USE Aeroporto

CREATE TABLE Passageiro(
IDPASSAGEIRO int PRIMARY KEY IDENTITY(1,1),
CPF varchar(11) NOT NULL,
NOME varchar(100) NOT NULL,
SOBRENOME varchar(100) NOT NULL
);

CREATE TABLE Aeroporto(
IDAEROPORTO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) NOT NULL,
CIDADE varchar(100) NOT NULL,
ESTADO varchar(2) NOT NULL,
SIGLA varchar(3) NOT NULL
)

CREATE TABLE Aeronave(
IDAERONAVE int PRIMARY KEY IDENTITY(1,1),
MODELO varchar(4) NOT NULL,
CAPACIDADE int,
CONSTRAINT CK_CAPACIDADE CHECK (CAPACIDADE > 0)
);

CREATE TABLE Voo(
IDVOO int PRIMARY KEY IDENTITY(1,1),
ORIGEM INT CONSTRAINT NN_ORIGEM_VOO NOT NULL,
DESTINO int CONSTRAINT NN_DESTINO_VOO NOT NULL,
AERONAVE int CONSTRAINT NN_ID_AERONAVE NOT NULL,
CONSTRAINT FK_COD_ORIGEM FOREIGN KEY (ORIGEM) REFERENCES AEROPORTO (IDAEROPORTO),
CONSTRAINT FK_COD_DESTINO FOREIGN KEY (DESTINO) REFERENCES AEROPORTO (IDAEROPORTO),
CONSTRAINT FK_COD_AERONAVE FOREIGN KEY (AERONAVE) REFERENCES AERONAVE (IDAERONAVE),
DATA_VOO DATETIME CONSTRAINT NN_DATA_VOO NOT NULL,
PORTAOEMBARQUE varchar(3) CONSTRAINT NN_PORTAOEMBARQUE NOT NULL
);