CREATE DATABASE Exercicio01;

CREATE TABLE Projeto(
NUM_PROJETO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) NOT NULL,
LOCALIZACAO varchar(100) NOT NULL
);

CREATE TABLE Empregado(
RG varchar(10) PRIMARY KEY NOT NULL,
NOME varchar(100) NOT NULL,
CPF varchar(11) NOT NULL,
NUM_DEPTO int NOT NULL,
-- CONSTRAINT FK_EMPREGADOS_DEPTO FOREIGN KEY (NUM_DEPTO)
-- REFERENCES DEPARTAMENTO(NUM_DEPTO),
RG_SUPERVISOR varchar(10) NULL,
SALARIO decimal(10,2) NOT NULL
);

CREATE TABLE Departamento(
NUM_DEPTO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) NOT NULL,
RG_GERENTE varchar(10) NOT NULL,
-- CONSTRAINT FK_DEPARTAMENTO_RG_GERENTE FOREIGN KEY (RG_GERENTE)
-- REFERENCES EMPREGADO(RG_SUPERVISOR)
);

ALTER TABLE Empregado
ADD CONSTRAINT FK_EMPREGADO_DEPTO FOREIGN KEY (NUM_DEPTO)
REFERENCES Departamento(NUM_DEPTO);

ALTER TABLE Departamento
ADD CONSTRAINT FK_DEPARTAMENTO_RG_GERENTE FOREIGN KEY (RG_GERENTE)
REFERENCES EMPREGADO(RG);

ALTER TABLE Empregado
ADD CONSTRAINT FK_EMPREGADO_SUPERVISOR FOREIGN KEY (RG_SUPERVISOR)
REFERENCES EMPREGADO(RG);

CREATE TABLE Dependentes(
RG_RESPONSAVEL varchar(10),
NOME_DEPENDENTE varchar(10) PRIMARY KEY NOT NULL,
CONSTRAINT FK_DEPENDENTES_RG_RESPONSAVEL FOREIGN KEY (RG_RESPONSAVEL)
REFERENCES EMPREGADO(RG),
DT_NASCIMENTO date,
RELACAO varchar(20),
SEXO varchar(10)
);

CREATE TABLE Departamento_Projeto(
NUM_DEPTO int NOT NULL,
NUM_PROJETO int NOT NULL,
CONSTRAINT PK_DEPTO_PROJETO PRIMARY KEY (NUM_DEPTO, NUM_PROJETO), -- PK composta
CONSTRAINT FK_DEPTO_PROJETO_DEPTO FOREIGN KEY (NUM_DEPTO)
REFERENCES DEPARTAMENTO(NUM_DEPTO),
CONSTRAINT FK_DEPTO_PROJETO_PROJETO FOREIGN KEY (NUM_PROJETO)
REFERENCES PROJETO(NUM_PROJETO)
);

CREATE TABLE Empregado_Projeto(
RG_EMPREGADO varchar(10) NOT NULL,
NUM_PROJETO int NOT NULL,
HORAS int NOT NULL, -- Mude para INT (é um número, não texto)
CONSTRAINT PK_EMPREGADO_PROJETO PRIMARY KEY (RG_EMPREGADO, NUM_PROJETO), -- PK composta
CONSTRAINT FK_EMPREGADO_PROJETO_EMPREGADO FOREIGN KEY (RG_EMPREGADO)
REFERENCES EMPREGADO(RG),
CONSTRAINT FK_EMPREGADO_PROJETO_PROJETO FOREIGN KEY (NUM_PROJETO)
REFERENCES PROJETO(NUM_PROJETO)
);

