--------------- LISTA EXERCÍCIOS SUBQUERRIES AVANÇADAS ---------------------

--1. Liste autores cujos livros têm preço acima da média geral.
SELECT AUTOR
FROM LIVRO
WHERE PRECO > (SELECT AVG(PRECO) FROM LIVRO);
--2. Encontre livros publicados no mesmo ano do livro mais antigo.
SELECT ID_LIVRO, TITULO, AUTOR, ANO_PUBLICACAO
FROM LIVRO
WHERE ANO_PUBLICACAO IN (
	SELECT MIN (ANO_PUBLICACAO) FROM LIVRO);
--3. Liste usuários que pegaram livros mais caros que R$ 80.
SELECT ID_USUARIO, NOME_USUARIO, DATA_CADASTRO
FROM USUARIO
WHERE ID_USUARIO IN (
	SELECT ID_USUARIO
	FROM EMPRESTIMO 
	WHERE ID_USUARIO IN (
		SELECT ID_USUARIO
		FROM LIVRO
		WHERE PRECO>80));
--4. Encontre editoras que têm livros mais baratos que a média.
SELECT ID_EDITORA, NOME_EDITORA, CIDADE, PAIS
FROM EDITORA
WHERE ID_EDITORA IN (
	SELECT ID_EDITORA
	FROM LIVRO
	WHERE PRECO < (
		SELECT AVG(PRECO) FROM LIVRO));
--5. Selecione livros de autores que também escreveram "1984".
SELECT ID_LIVRO, TITULO, AUTOR, ANO_PUBLICACAO, GENERO, PRECO, ID_EDITORA
FROM LIVRO
WHERE AUTOR IN (
	SELECT AUTOR
	FROM LIVRO
	WHERE TITULO = '1984');
--6. Liste empréstimos de usuários que se cadastraram em 2024.
SELECT ID_EMPRESTIMO, ID_LIVRO, ID_USUARIO, DATA_EMPRESTIMO, DATA_DEVOLUCAO
FROM EMPRESTIMO
WHERE ID_USUARIO IN (
	SELECT ID_USUARIO
	FROM USUARIO
	WHERE DATA_CADASTRO = '2024');
--7. Encontre livros de editoras que publicaram "Dom Casmurro".
SELECT ID_LIVRO, TITULO, AUTOR, ANO_PUBLICACAO, GENERO, PRECO
FROM LIVRO
WHERE ID_EDITORA = (
	SELECT ID_EDITORA
	FROM LIVRO
	WHERE TITULO LIKE 'Dom Casmurro');
--8. Selecione usuários que pegaram livros da mesma editora que publicou "O Cortiço".
SELECT ID_USUARIO, NOME_USUARIO, EMAIL, TELEFONE, DATA_CADASTRO
FROM USUARIO
WHERE ID_USUARIO IN (
	SELECT ID_USUARIO
	FROM EMPRESTIMO
	WHERE ID_LIVRO IN (
		SELECT ID_LIVRO
		FROM LIVRO
		WHERE ID_EDITORA IN (
			SELECT ID_EDITORA
			FROM LIVRO
			WHERE TITULO LIKE 'O Cortiço')));
--9. Liste livros publicados no mesmo ano que "Harry Potter e a Pedra Filosofal".
SELECT ID_LIVRO, TITULO, AUTOR, ANO_PUBLICACAO, GENERO, PRECO, ID_EDITORA
FROM LIVRO
WHERE ANO_PUBLICACAO IN (
	SELECT ANO_PUBLICACAO
	FROM LIVRO
	WHERE TITULO LIKE 'Harry Potter e a Pedra Filosofal');
--10. Encontre empréstimos de livros que custam mais que "O Pequeno Príncipe".
SELECT ID_EMPRESTIMO, ID_LIVRO, ID_USUARIO, DATA_EMPRESTIMO, MULTA
FROM EMPRESTIMO
WHERE ID_LIVRO IN (
	SELECT ID_LIVRO
	FROM LIVRO
	WHERE PRECO > (SELECT PRECO FROM LIVRO WHERE TITULO LIKE 'O Pequeno Príncipe'));