CREATE TABLE Estados(
COD_ESTADO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) UNIQUE NOT NULL
);

CREATE TABLE Tipo_Conta(
COD_TIPO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) UNIQUE NOT NULL
);

CREATE TABLE Tipo_Emprestimo(
COD_TIPO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) UNIQUE NOT NULL
);

CREATE TABLE Cidades(
COD_CIDADE int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) UNIQUE NOT NULL,
COD_ESTADO int NOT NULL,
CONSTRAINT FK_CIDADES_ESTADOS FOREIGN KEY (COD_ESTADO)
REFERENCES ESTADOS(COD_ESTADO)
);

CREATE TABLE Bancos(
COD_BANCO int PRIMARY KEY IDENTITY(1,1),
NOME varchar(100) NOT NULL,
RUA varchar(100) NOT NULL,
NUMERO varchar(100) NOT NULL,
BAIRRO varchar(100) NOT NULL,
COMPLEMENTO varchar(100)NULL,
COD_CIDADE int NOT NULL,
CONSTRAINT FK_BANCOS_CIDADES FOREIGN KEY (COD_CIDADE)
REFERENCES CIDADES(COD_CIDADE)
);

CREATE TABLE Clientes(
CPF varchar(11) PRIMARY KEY,
NOME varchar(100) NOT NULL,
RUA varchar(100) NOT NULL,
NUMERO varchar(100) NOT NULL,
BAIRRO varchar(100) NOT NULL,
COMPLEMENTO varchar(100)NULL,
COD_CIDADE int NOT NULL,
CONSTRAINT FK_CLIENTES_CIDADES FOREIGN KEY (COD_CIDADE)
REFERENCES CIDADES(COD_CIDADE)
);

CREATE TABLE Telefones(
COD_TELEFONE int PRIMARY KEY IDENTITY(1,1),
DDD varchar(3) NOT NULL,
NUMERO varchar(9) NOT NULL,
CPF varchar(11) NOT NULL,
CONSTRAINT FK_TELEFONES_CLIENTES FOREIGN KEY (CPF)
REFERENCES CLIENTES(CPF)
)

CREATE TABLE Agencias(
NUM_AGENCIA int PRIMARY KEY IDENTITY(1,1),
RUA varchar(100) NOT NULL,
BAIRRO varchar(100) NOT NULL,
COMPLEMENTO varchar(100) NULL,
COD_CIDADE int NOT NULL,
COD_BANCO int NOT NULL,
CONSTRAINT FK_AGENCIAS_CIDADES FOREIGN KEY (COD_CIDADE)
REFERENCES CIDADES(COD_CIDADE),
CONSTRAINT FK_AGENCIAS_BANCOS FOREIGN KEY (COD_BANCO)
REFERENCES BANCOS(COD_BANCO)
);

CREATE TABLE Contas(
NUM_CONTA int PRIMARY KEY IDENTITY(1,1),
SALDO decimal(10,2) NULL,
COD_TIPO int NOT NULL,
NUM_AGENCIA int NOT NULL,
CONSTRAINT FK_CONTAS_TIPOS FOREIGN KEY (COD_TIPO)
REFERENCES TIPO_CONTA(COD_TIPO),
CONSTRAINT FK_CONTAS_AGENCIAS FOREIGN KEY (NUM_AGENCIA)
REFERENCES AGENCIAS(NUM_AGENCIA)
);

CREATE TABLE Emprestimos(
NUM_EMP int PRIMARY KEY IDENTITY(1,1),
QUANTIA int NOT NULL,
COD_TIPO int NOT NULL,
NUM_AGENCIA int NOT NULL,
CONSTRAINT FK_EMPRESTIMOS_TIPOS FOREIGN KEY (COD_TIPO)
REFERENCES TIPO_EMPRESTIMO(COD_TIPO),
CONSTRAINT FK_EMPRESTIMOS_AGENCIA FOREIGN KEY (NUM_AGENCIA)
REFERENCES AGENCIAS(NUM_AGENCIA)
);

CREATE TABLE Conta_Cliente(
NUM_CONTA int NOT NULL,
CPF varchar(11) NOT NULL,
CONSTRAINT PK_CONTA_CLIENTE PRIMARY KEY (NUM_CONTA, CPF),
CONSTRAINT FK_CONTA_CLIENTE_CONTA FOREIGN KEY (NUM_CONTA)
REFERENCES CONTAS(NUM_CONTA),
CONSTRAINT FK_CONTA_CLIENTE_CPF FOREIGN KEY (CPF)
REFERENCES CLIENTES(CPF)
);

CREATE TABLE Emprestimo_Cliente(
NUM_EMP int NOT NULL,
CPF varchar(11) NOT NULL,
CONSTRAINT PK_EMPRESTIMO_CLIENTE PRIMARY KEY (NUM_EMP, CPF),
CONSTRAINT FK_EMPRESTIMO_CLIENTE_NUM_EMP FOREIGN KEY (NUM_EMP)
REFERENCES EMPRESTIMOS(NUM_EMP),
CONSTRAINT FK_EMPRESTIMO_CLIENTE_CPF FOREIGN KEY (CPF)
REFERENCES CLIENTES(CPF)
);
