-- LEFT JOIN
--1. Liste todos os livros e suas editoras (inclua livros sem editora).
SELECT L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.GENERO, L.PRECO, E.NOME_EDITORA, E.PAIS
FROM LIVRO L
LEFT JOIN EDITORA E ON L.ID_EDITORA = E.ID_EDITORA
--2. Mostre todos os usuários e seus empréstimos (inclua usuários sem empréstimos).
SELECT U.ID_USUARIO, U.NOME_USUARIO, U.EMAIL, U.TELEFONE, E.ID_EMPRESTIMO, E.DATA_EMPRESTIMO, E.DATA_DEVOLUCAO
FROM USUARIO U
LEFT JOIN EMPRESTIMO E ON U.ID_USUARIO = E.ID_USUARIO
--3. Liste todas as editoras e seus livros (inclua editoras sem livros).
SELECT E.ID_EDITORA, E.NOME_EDITORA, L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.PRECO
FROM EDITORA E
LEFT JOIN LIVRO L ON L.ID_EDITORA = E.ID_EDITORA
ORDER BY E.NOME_EDITORA;
--4. Mostre todos os livros e empréstimos (inclua livros nunca emprestados).
SELECT L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.GENERO, L.PRECO, E.ID_USUARIO, E.DATA_EMPRESTIMO, E.DATA_DEVOLUCAO, E.MULTA
FROM LIVRO L
LEFT JOIN EMPRESTIMO E ON L.ID_LIVRO = E.ID_LIVRO
ORDER BY L.TITULO;
--5. Liste usuários e total de empréstimos (inclua quem nunca pegou).
SELECT U.ID_USUARIO, U.NOME_USUARIO, U.EMAIL, U.TELEFONE, U.DATA_CADASTRO,
	COUNT(E.ID_EMPRESTIMO) AS TOTAL_EMPRESTIMOS
FROM USUARIO U
LEFT JOIN EMPRESTIMO E ON E.ID_USUARIO = U.ID_USUARIO
GROUP BY U.ID_USUARIO, U.NOME_USUARIO, U.EMAIL, U.TELEFONE, U.DATA_CADASTRO;
--6. Mostre editoras e quantidade de livros (inclua editoras sem livros).
SELECT E.ID_EDITORA, E.NOME_EDITORA, E.CIDADE, E.PAIS, COUNT(L.ID_LIVRO) AS LIVROS_TOTAIS
FROM LIVRO L
LEFT JOIN EDITORA E ON E.ID_EDITORA = L.ID_EDITORA
GROUP BY E.ID_EDITORA, E.NOME_EDITORA, E.CIDADE, E.PAIS;
--7. Liste livros e data do último empréstimo (inclua nunca emprestados).
SELECT L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.GENERO, L.PRECO, MAX(E.DATA_EMPRESTIMO) AS ULTIMO_EMPRESTIMO
FROM LIVRO L
LEFT JOIN EMPRESTIMO E ON L.ID_LIVRO = E.ID_LIVRO
GROUP BY L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.GENERO, L.PRECO;
--8. Mostre todos os autores e suas editoras (inclua autores sem editora).
SELECT L.AUTOR, E.NOME_EDITORA
FROM LIVRO L
LEFT JOIN EDITORA E ON L.ID_EDITORA = E.ID_EDITORA;
--9. Liste usuários e valor total de multas (inclua sem multas).
SELECT U.NOME_USUARIO, U.EMAIL, U.TELEFONE, U.DATA_CADASTRO, SUM(E.MULTA) AS TOTAL_MULTAS
FROM USUARIO U
LEFT JOIN EMPRESTIMO E ON U.ID_USUARIO = E.ID_USUARIO
GROUP BY U.NOME_USUARIO, U.EMAIL, U.TELEFONE, U.DATA_CADASTRO;
--10.Mostre livros e total arrecadado em multas (inclua sem multas).
SELECT L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.GENERO, L.PRECO, SUM(E.MULTA) AS TOTAL_MULTAS
FROM LIVRO L
LEFT JOIN EMPRESTIMO E ON L.ID_LIVRO = E.ID_LIVRO
GROUP BY L.TITULO, L.AUTOR, L.ANO_PUBLICACAO, L.GENERO, L.PRECO;